# RepData_PeerAss_2
library(R.utils)
library(ggplot2)
library(plyr)
library(gridExtra)

setwd("C:/Users/Tinoco/Google Drive/2. Research (Current)/(2015) Courses/(2015) Especialization in Data Science_/5. Reproducible Research/Week 3/Project 3")  
#stormData <- read.csv("repdata-data-StormData.csv", colClasses = "character")
stormData <- read.csv("repdata-data-StormData.csv", sep = ",")
options(scipen = 1) 
dim(stormData)
#stormData = data.table(stormData)

#############################
if (dim(stormData)[2] == 37) {
  stormData$year <- as.numeric(format(as.Date(stormData$BGN_DATE, format = "%m/%d/%Y %H:%M:%S"), "%Y"))
}
hist(stormData$year, breaks = 30, col="red", xlab="Year", ylab="Numbers of Events", main="Events")
########################################

DataS=stormData[stormData$year>= 1990, ]
#DataL=data.table(DataS)
StormL=dim(DataS)


## Function to order data
sortFF <- function(fieldName, top = 10, dataset = stormData) {
  index <- which(colnames(dataset) == fieldName)
  field <- aggregate(dataset[, index], by = list(dataset$EVTYPE), FUN = "sum")
  names(field) <- c("EVTYPE", fieldName)
  field <- arrange(field, field[, 2], decreasing = T)
  field <- head(field, n = top)
  field <- within(field, EVTYPE <- factor(x = EVTYPE, levels = field$EVTYPE))
  return(field)
  
}
  
# Injured and dead People

fatal=sortFF("FATALITIES", dataset = DataS)
inju=sortFF("INJURIES", dataset = DataS)


# FactorH <- function(dataset = DataS, fieldName, newFieldName) {
#   totalLen <- dim(dataset)[2]
#   index <- which(colnames(dataset) == fieldName)
#   dataset[, index] <- as.character(dataset[, index])
#   logic <- !is.na(toupper(dataset[, index]))
#   dataset[logic & toupper(dataset[, index]) == "B", index] <- "9"
#   dataset[logic & toupper(dataset[, index]) == "M", index] <- "6"
#   dataset[logic & toupper(dataset[, index]) == "K", index] <- "3"
#   dataset[logic & toupper(dataset[, index]) == "H", index] <- "2"
#   dataset[logic & toupper(dataset[, index]) == "", index] <- "0"
#   dataset[, index] <- as.numeric(dataset[, index])
#   dataset[is.na(dataset[, index]), index] <- 0
#   dataset <- cbind(dataset, dataset[, index - 1] * 10^dataset[, index])
#   names(dataset)[totalLen + 1] <- newFieldName
#   return(dataset)
# }
# 
# ##################################################################
# 
# storm <- FactorH(DataS, "PROPDMGEXP", "propertyDamage")
# storm <- FactorH(DataS, "CROPDMGEXP", "cropDamage")
# options(scipen=999)
# properties <- sortFF("propertyDamage", dataset = storm)
# crops <- sortFF("cropDamage", dataset = storm)

#############################################################
## Results 1
#############################################################
qplot(EVTYPE, data = fatal, weight = FATALITIES, geom = "bar", binwidth = 1, ylab="Number of Fatalities",xlab= "Event Type") + 
 ggtitle("Total Fatalities by Weather\n Events 1990-2011")

qplot(EVTYPE, data = inju, weight = INJURIES, geom = "bar", binwidth = 1) + 
  scale_y_continuous("Number of Injuries") + 
  xlab("Severe Weather Type") + 
  ggtitle("Total Fatalities by Weather\n Events between 1990-2011")

#############################################################
## Results 2
# #############################################################
# propertyPlot <- qplot(EVTYPE, data = property, weight = propertyDamage, geom = "bar", binwidth = 1) + 
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_y_continuous("Property Damage in US dollars")+ 
#   xlab("Severe Weather Type") + ggtitle("Total Property Damage by\n Severe Weather Events in\n the U.S. from 1995 - 2011")
# 
# cropPlot<- qplot(EVTYPE, data = crop, weight = cropDamage, geom = "bar", binwidth = 1) + 
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_y_continuous("Crop Damage in US dollars") + 
#   xlab("Severe Weather Type") + ggtitle("Total Crop Damage by \nSevere Weather Events in\n the U.S. from 1995 - 2011")
# grid.arrange(propertyPlot, cropPlot, ncol = 2)
# 


# Fatalities

#Q1=tapply(as.numeric(Data[,23]),Data[,8],sum)

# people Injured

#Q2=tapply(as.numeric(Data[,24]),Data[,8],sum)
#Qn1=Q1[(Q1>0)];
#Qn2=Q2[(Q2>0)];

#MFm=which.max((Qn1))
#MIm=which.max((Qn2))
#MFi=which.min((Qn1))
#MIi=which.min((Qn2))

#hist(Qn1,freq=TRUE,breaks=length(Qn1),col="red", xlab="Total steps by Day", ylab="Frequency of Steps", main="Mean of Steps")
#hist(Qn2,freq=TRUE,breaks=length(Qn2),col="red", xlab="Total steps by Day", ylab="Frequency of Steps", main="Mean of Steps")

